// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: schemas.proto

/* eslint-disable */

export const protobufPackage = "EulerStreamWebSocketClient";

export enum WebcastSchemaVersion {
  SCHEMA_VERSION_UNSPECIFIED = 0,
  SCHEMA_VERSION_V1 = 1,
  SCHEMA_VERSION_V2 = 2,
  SCHEMA_VERSION_V3 = 3,
  UNRECOGNIZED = -1,
}

export enum WebcastPlatform {
  WEBCAST_PLATFORM_UNSPECIFIED = 0,
  WEBCAST_PLATFORM_WEB = 1,
  WEBCAST_PLATFORM_MOBILE = 2,
  UNRECOGNIZED = -1,
}

export enum ClientCloseCode {
  CLIENT_CLOSE_CODE_UNSPECIFIED = 0,
  CLIENT_CLOSE_CODE_NORMAL = 1000,
  CLIENT_CLOSE_CODE_INTERNAL_SERVER_ERROR = 1011,
  CLIENT_CLOSE_CODE_STREAM_END = 4005,
  CLIENT_CLOSE_CODE_NO_MESSAGES_TIMEOUT = 4006,
  CLIENT_CLOSE_CODE_INVALID_OPTIONS = 4400,
  CLIENT_CLOSE_CODE_INVALID_AUTH = 4401,
  CLIENT_CLOSE_CODE_NO_PERMISSION = 4403,
  CLIENT_CLOSE_CODE_NOT_LIVE = 4404,
  CLIENT_CLOSE_CODE_TOO_MANY_CONNECTIONS = 4429,
  CLIENT_CLOSE_CODE_TIKTOK_CLOSED_CONNECTION = 4500,
  CLIENT_CLOSE_CODE_MAX_LIFETIME_EXCEEDED = 4555,
  CLIENT_CLOSE_CODE_WEBCAST_FETCH_ERROR = 4556,
  CLIENT_CLOSE_CODE_ROOM_INFO_FETCH_ERROR = 4557,
  UNRECOGNIZED = -1,
}

export enum RoomStatusEventState {
  ROOM_STATUS_STATE_UNSPECIFIED = 0,
  ROOM_STATUS_STATE_CONNECTING = 1,
  ROOM_STATUS_STATE_CONNECTED = 2,
  ROOM_STATUS_STATE_RECONNECTING = 3,
  ROOM_STATUS_STATE_OFFLINE = 4,
  ROOM_STATUS_STATE_ENDED = 5,
  ROOM_STATUS_STATE_ERROR = 6,
  UNRECOGNIZED = -1,
}

export enum LocalRoomState {
  LOCAL_ROOM_STATE_UNSPECIFIED = 0,
  LOCAL_ROOM_STATE_OWNED = 1,
  LOCAL_ROOM_STATE_IDLE = 3,
  UNRECOGNIZED = -1,
}

/** Client Options when configuring the WebSocket server gateway */
export interface WebSocketOptions {
  uniqueId: string;
  jwtKey?: string | undefined;
  apiKey?: string | undefined;
  xCookieHeader?: string | undefined;
  xOauthToken?:
    | string
    | undefined;
  /** WebSocket feature flags */
  features:
    | WebSocketFeatureFlags
    | undefined;
  /** WebSocket gateway flags */
  flags: WebSocketGatewayFlags | undefined;
}

export interface WebSocketGatewayFlags {
  /** Whether the gateway will bundle events or emit individually */
  bundleEvents?:
    | boolean
    | undefined;
  /** The output schema version */
  schemaVersion?:
    | WebcastSchemaVersion
    | undefined;
  /** Whether the gateway will output raw binary or JSON */
  rawMessages?:
    | boolean
    | undefined;
  /** Whether to include raw bytes as base64 in the JSON when raw_messages = false */
  includeRawBytes?: boolean | undefined;
}

export interface WebSocketFeatureFlags {
  /** Whether to normalize the Unique ID value */
  normalizeUniqueId?:
    | boolean
    | undefined;
  /** Whether to use the Enterprise API when connecting */
  useEnterpriseApi?:
    | boolean
    | undefined;
  /** Platform to use */
  webcastPlatform: WebcastPlatform;
  /**
   * Whether the gateway should also attach the client to the peer
   * transcription stream for this creator.
   */
  enableTranscription?: boolean | undefined;
}

export interface WebSocketServerEvent {
  metadata: WebSocketServerEvent_WebSocketServerEventMetadata | undefined;
  tiktokProtoEvent?: TikTokProtoEvent | undefined;
  customEvent?: TikTokJsonEvent | undefined;
  connectEvent?: TikTokConnectEvent | undefined;
  roomStatusEvent?: RoomStatusEvent | undefined;
  transcriptionEvent?: TranscriptionEvent | undefined;
  transcriptionStatusEvent?: TranscriptionStatusEvent | undefined;
}

export interface WebSocketServerEvent_WebSocketServerEventMetadata {
  timestampUnixMs: string;
}

/** Events that define a JSON or alias schema */
export interface TikTokJsonEvent {
  /** Event Name */
  type: string;
  /** Event JSON */
  json: string;
}

export interface TikTokProtoEvent {
  /** Protobuf name for deserialization */
  type: string;
  /** Protobuf binary for deserialization */
  payload: Uint8Array;
  /** Alias (e.g. for superFan & other custom events) */
  alias?: string | undefined;
}

export interface TikTokConnectEvent {
  agentId: string;
}

export interface TikTokDisconnectEvent {
  /** Close code that resulted in this message */
  closeCode: ClientCloseCode;
}

export interface RoomStatusEvent {
  /** 'connecting' | 'connected' | 'reconnecting' | 'offline' | 'ended' | 'error' */
  state: RoomStatusEventState;
  /** Room ID connected to */
  roomId?:
    | string
    | undefined;
  /** What attempt # is the event */
  attempt?:
    | number
    | undefined;
  /** Close code that resulted in this message */
  closeCode?:
    | ClientCloseCode
    | undefined;
  /** Whether the close code is terminal (else reconnecting) */
  closeCodeTerminal?:
    | boolean
    | undefined;
  /** A message shipped with the close code, if applicable */
  closeCodeMessage?: string | undefined;
}

export interface TranscriptionEvent {
  /** Final or partial transcript text from the peer transcription */
  text: string;
  /** Whether this transcript segment is final. */
  isFinal: boolean;
  /** Optional language/model/provider details from the transcription backend. */
  language?: string | undefined;
  provider?:
    | string
    | undefined;
  /** Optional timing metadata in seconds relative to the live audio stream. */
  startTimeSeconds?: number | undefined;
  endTimeSeconds?:
    | number
    | undefined;
  /** Opaque provider or server generated segment id. */
  transcriptId?: string | undefined;
}

export interface TranscriptionStatusEvent {
  /** 'starting' | 'connected' | 'reconnecting' | 'ended' | 'error' */
  state: string;
  provider?: string | undefined;
  message?: string | undefined;
  terminal?: boolean | undefined;
}

export interface WorkerInfoEvent {
  registerId: string;
  /** Mirrored back upon gateway join */
  schemaVersion: WebcastSchemaVersion;
  features:
    | WebSocketFeatureFlags
    | undefined;
  /** Mirrored as well, equivalent to isLoggedIn */
  sessionDetailsProvided: boolean;
}
